name: React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile

      - name: Run tests
        run: |
          yarn test --watchAll=false
