name: Deploy to AWS

on:
  workflow_run:
    workflows: ["React Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Vérifie si les tests ont réussi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Ajouter la clé de l'hôte à known_hosts pour éviter les erreurs de vérification
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy application
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd /home/${{ secrets.SSH_USER }}/project-AWS-/mon-app
            git pull origin main
            docker-compose down
            docker system prune -af
            docker image prune -af
            docker-compose up -d --build
          EOF
